[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16.14.0"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 